"""fix: delete filed 'is admin' from membership

Revision ID: 0e6455af1bf1
Revises: 02a52003f7a3
Create Date: 2025-04-13 17:14:08.982106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e6455af1bf1'
down_revision: Union[str, None] = '02a52003f7a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memberships', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
