"""update: model meeting

Revision ID: 626c8f551251
Revises: b3913d03cd49
Create Date: 2025-04-14 21:50:38.590585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '626c8f551251'
down_revision: Union[str, None] = 'b3913d03cd49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_participants')
    op.add_column('meetings', sa.Column('team_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'team_id')
    op.create_table('meeting_participants',
    sa.Column('meeting_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name='meeting_participants_meeting_id_fkey'),
    sa.PrimaryKeyConstraint('meeting_id', 'user_id', name='meeting_participants_pkey')
    )
    # ### end Alembic commands ###
